server:
  port: 8090

spring:
  application:
    name: security-springboot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

    resources:
      static-locations: classpath:/bootstrap/

    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      content-type: text/html
      #set to false for hot refresh
      cache: false

  main:
    allow-bean-definition-overriding: true   #允许bean覆盖

mybatis:
  mapper-locations: mapper/*.xml

